'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Servicios
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Servicios.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ComprobarRut", ReplyAction:="http://tempuri.org/IService1/ComprobarRutResponse")>  _
        Function ComprobarRut(ByVal rut As Integer, ByVal digito As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ComprobarRut", ReplyAction:="http://tempuri.org/IService1/ComprobarRutResponse")>  _
        Function ComprobarRutAsync(ByVal rut As Integer, ByVal digito As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/MostrarNombre", ReplyAction:="http://tempuri.org/IService1/MostrarNombreResponse")>  _
        Function MostrarNombre(ByVal nombre As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/MostrarNombre", ReplyAction:="http://tempuri.org/IService1/MostrarNombreResponse")>  _
        Function MostrarNombreAsync(ByVal nombre As String) As System.Threading.Tasks.Task(Of String())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits Servicios.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of Servicios.IService1)
        Implements Servicios.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ComprobarRut(ByVal rut As Integer, ByVal digito As String) As Boolean Implements Servicios.IService1.ComprobarRut
            Return MyBase.Channel.ComprobarRut(rut, digito)
        End Function
        
        Public Function ComprobarRutAsync(ByVal rut As Integer, ByVal digito As String) As System.Threading.Tasks.Task(Of Boolean) Implements Servicios.IService1.ComprobarRutAsync
            Return MyBase.Channel.ComprobarRutAsync(rut, digito)
        End Function
        
        Public Function MostrarNombre(ByVal nombre As String) As String() Implements Servicios.IService1.MostrarNombre
            Return MyBase.Channel.MostrarNombre(nombre)
        End Function
        
        Public Function MostrarNombreAsync(ByVal nombre As String) As System.Threading.Tasks.Task(Of String()) Implements Servicios.IService1.MostrarNombreAsync
            Return MyBase.Channel.MostrarNombreAsync(nombre)
        End Function
    End Class
End Namespace
